

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const FETCH_USERS_START = "FETCH_USERS_START";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FETCH_USER_START = "FETCH_USER_START";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_START = "UPDATE_USER_START";
export const START_UPDATE = "START_UPDATE";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_START = "DELETE_USER_START";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_START = "CREATE_USER_START";
export const NEW_USER_START = "NEW_USER_START";
export const NEW_USER_FAIL = "NEW_USER_FAIL";
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS";



export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";
export const FETCH_TASKS_START = "FETCH_TASKS_START";

export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAIL = "FETCH_TASK_FAIL";
export const FETCH_TASK_START = "FETCH_TASK_START";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const UPDATE_TASK_START = "UPDATE_TASK_START";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const DELETE_TASK_START = "DELETE_TASK_START";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const CREATE_TASK_START = "CREATE_TASK_START";
export const NEW_TASK_START = "NEW_TASK_START";
export const NEW_TASK_FAIL = "NEW_TASK_FAIL";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";
export const FETCH_USERTASKS_SUCCESS = "FETCH_USERTASKS_SUCCESS";
export const FETCH_USERTASKS_FAIL = "FETCH_USERTASKS_FAIL";
